import logging
from sqlalchemy.orm import Session
from datetime import datetime
from app.db.session import SessionLocal
from app.repositories.options_repo import OptionsRepository
from app.repositories.portfolio_repo import PortfolioRepository
from app.repositories.upside12m_repo import Upside12MRepository
from app.repositories.market_repo import MarketRepository
from app.services.options_suggestion_service import OptionsSuggestionService

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("CC_AUDIT")

def cc_audit():
    db = SessionLocal()
    repo = OptionsRepository(db)
    portfolio_repo = PortfolioRepository(db)
    upside_repo = Upside12MRepository(db)
    
    policy = repo.get_active_policy()
    positions = portfolio_repo.get_positions()
    
    print("\n" + "="*100)
    print(f"{'Ticker':<10} | {'Qty':<8} | {'AllowCC':<8} | {'Ingested':<10} | {'DTE':<6} | {'Delta':<6} | {'Liq':<6} | {'Thesis':<6} | {'Final'}")
    print("-" * 100)
    
    for pos in positions:
        ticker = pos.ticker
        qty = pos.quantity
        allow = pos.allow_covered_call
        
        chain = repo.get_latest_chain(ticker)
        ingested = len(chain)
        
        # Stages
        pass_dte = 0
        pass_delta = 0
        pass_liq = 0
        pass_thesis = 0
        
        service = OptionsSuggestionService(db)
        
        # Manual trace of the filter stage logic
        for opt in chain:
            if opt.option_type != "CALL": continue
            
            # 1. DTE
            if not (policy.min_dte <= opt.dte <= policy.max_dte): continue
            pass_dte += 1
            
            # 2. Delta
            delta = opt.delta or 0.0 # simplified for audit
            if not (policy.covered_call_delta_min <= abs(delta) <= policy.covered_call_delta_max): continue
            pass_delta += 1
            
            # 3. Liquidity
            if (opt.open_interest or 0) < policy.min_open_interest: continue
            pass_liq += 1
            
            # 4. Thesis (simplified)
            pass_thesis += 1
            
        # Final suggestions generated by service
        sugs = service._filter_and_score_options(
            ticker=ticker,
            chain=chain,
            policy=policy,
            suggestion_type="COVERED_CALL",
            available_lots=int(qty // 100)
        )
        final_count = len(sugs)
        
        print(f"{ticker:<10} | {qty:<8.0f} | {str(allow):<8} | {ingested:<10} | {pass_dte:<6} | {pass_delta:<6} | {pass_liq:<6} | {pass_thesis:<6} | {final_count}")

    db.close()

if __name__ == "__main__":
    cc_audit()
