"""Add upside12m models

Revision ID: 2b8a29453cb0
Revises: 6e596b4cf88c
Create Date: 2026-04-21 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8a29453cb0'
down_revision: Union[str, Sequence[str], None] = '6e596b4cf88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upside_12m_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('upside_ext_raw', sa.Float(), nullable=False),
    sa.Column('rerating_raw', sa.Float(), nullable=False),
    sa.Column('recup_operacional_raw', sa.Float(), nullable=False),
    sa.Column('assimetria_raw', sa.Float(), nullable=False),
    sa.Column('gov_liq_raw', sa.Float(), nullable=False),
    sa.Column('penalties_raw', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('rating_class', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), server_default='v1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'as_of_date', name='uq_upside12m_snapshot')
    )
    op.create_index(op.f('ix_upside_12m_snapshots_as_of_date'), 'upside_12m_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_upside_12m_snapshots_company_id'), 'upside_12m_snapshots', ['company_id'], unique=False)
    op.create_table('research_targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('rating_recommendation', sa.String(), nullable=False),
    sa.Column('current_price_snapshot', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_targets_company_id'), 'research_targets', ['company_id'], unique=False)
    op.create_table('upside_12m_rankings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('score_snapshot_id', sa.String(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('rating_class', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), server_default='v1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['score_snapshot_id'], ['upside_12m_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'as_of_date', name='uq_upside12m_ranking_company_date'),
    sa.UniqueConstraint('position', 'as_of_date', name='uq_upside12m_ranking_position_date')
    )
    op.create_index(op.f('ix_upside_12m_rankings_as_of_date'), 'upside_12m_rankings', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_upside_12m_rankings_company_id'), 'upside_12m_rankings', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upside_12m_rankings_company_id'), table_name='upside_12m_rankings')
    op.drop_index(op.f('ix_upside_12m_rankings_as_of_date'), table_name='upside_12m_rankings')
    op.drop_table('upside_12m_rankings')
    op.drop_index(op.f('ix_research_targets_company_id'), table_name='research_targets')
    op.drop_table('research_targets')
    op.drop_index(op.f('ix_upside_12m_snapshots_company_id'), table_name='upside_12m_snapshots')
    op.drop_index(op.f('ix_upside_12m_snapshots_as_of_date'), table_name='upside_12m_snapshots')
    op.drop_table('upside_12m_snapshots')
    # ### end Alembic commands ###
