"""Add market_cap and enterprise_value to MarketSnapshot

Revision ID: 4c11a6a96499
Revises: 9d7a1fd34a21
Create Date: 2026-04-21 08:41:55.763083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c11a6a96499'
down_revision: Union[str, Sequence[str], None] = '9d7a1fd34a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_snapshots', sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('market_snapshots', sa.Column('enterprise_value', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_snapshots', 'enterprise_value')
    op.drop_column('market_snapshots', 'market_cap')
    # ### end Alembic commands ###
