"""Hardening update

Revision ID: 6e596b4cf88c
Revises: b725abcef74e
Create Date: 2026-04-21 13:03:46.350857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e596b4cf88c'
down_revision: Union[str, Sequence[str], None] = 'b725abcef74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_logs_job_name'), 'job_logs', ['job_name'], unique=False)
    op.create_table('portfolio_cash',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_positions_ticker'), 'portfolio_positions', ['ticker'], unique=False)
    op.add_column('ranking_snapshots', sa.Column('model_version', sa.String(length=20), nullable=True))
    op.execute("UPDATE ranking_snapshots SET model_version = 'v1.0.0'")
    op.alter_column('ranking_snapshots', 'model_version', nullable=False)
    op.create_index(op.f('ix_ranking_snapshots_model_version'), 'ranking_snapshots', ['model_version'], unique=False)
    
    op.add_column('score_snapshots', sa.Column('model_version', sa.String(length=20), nullable=True))
    op.execute("UPDATE score_snapshots SET model_version = 'v1.0.0'")
    op.alter_column('score_snapshots', 'model_version', nullable=False)
    op.create_index(op.f('ix_score_snapshots_model_version'), 'score_snapshots', ['model_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_snapshots_model_version'), table_name='score_snapshots')
    op.drop_column('score_snapshots', 'model_version')
    op.drop_index(op.f('ix_ranking_snapshots_model_version'), table_name='ranking_snapshots')
    op.drop_column('ranking_snapshots', 'model_version')
    op.drop_index(op.f('ix_portfolio_positions_ticker'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_table('portfolio_cash')
    op.drop_index(op.f('ix_job_logs_job_name'), table_name='job_logs')
    op.drop_table('job_logs')
    # ### end Alembic commands ###
