"""Initial migration

Revision ID: 88c59fa2b702
Revises: 
Create Date: 2026-04-21 07:42:23.289055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c59fa2b702'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=32), nullable=True),
    sa.Column('cvm_code', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('listing_segment', sa.String(length=100), nullable=True),
    sa.Column('main_index', sa.String(length=50), nullable=True),
    sa.Column('free_float', sa.Numeric(), nullable=True),
    sa.Column('avg_daily_liquidity', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('sector_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('weight_quality', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_valuation', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_dividends', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_trend', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_gov_liq', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('use_debt_ebitda', sa.Boolean(), nullable=False),
    sa.Column('use_pb_strong', sa.Boolean(), nullable=False),
    sa.Column('use_dividend_strong', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_configs_sector'), 'sector_configs', ['sector'], unique=True)
    op.create_table('financials_annual',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cfo', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fcf', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('dividends', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebit_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roic', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('payout', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('bvps', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financials_annual_company_id'), 'financials_annual', ['company_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fcf_yield', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_5y_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb_5y_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ev_ebitda_5y_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sector_pe_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sector_pb_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sector_ev_ebitda_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('graham_number', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('graham_discount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('simple_fair_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fair_value_discount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_as_of_date'), 'market_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_market_snapshots_company_id'), 'market_snapshots', ['company_id'], unique=False)
    op.create_table('ranking_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=True),
    sa.Column('rating_class', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_snapshots_as_of_date'), 'ranking_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_ranking_snapshots_company_id'), 'ranking_snapshots', ['company_id'], unique=False)
    op.create_table('risk_flags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('non_recurring_profit_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recurring_negative_fcf_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('debt_up_income_down_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unsustainable_payout_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margin_deterioration_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('governance_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('binary_event_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accounting_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_flags_as_of_date'), 'risk_flags', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_risk_flags_company_id'), 'risk_flags', ['company_id'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('quality_raw', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valuation_raw', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dividends_raw', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trend_raw', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gov_liq_raw', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quality_weighted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valuation_weighted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dividends_weighted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trend_weighted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gov_liq_weighted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating_class', sa.String(length=50), nullable=True),
    sa.Column('bucket', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_snapshots_as_of_date'), 'score_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_score_snapshots_company_id'), 'score_snapshots', ['company_id'], unique=False)
    op.create_table('trend_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('revenue_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ebit_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_income_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ebit_margin_current', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ebit_margin_previous', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('margin_delta', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_debt_current', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_debt_previous', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('debt_delta', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('buyback_flag', sa.Boolean(), nullable=False),
    sa.Column('guidance_flag', sa.Boolean(), nullable=False),
    sa.Column('earnings_revision_flag', sa.Boolean(), nullable=False),
    sa.Column('improvement_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_snapshots_as_of_date'), 'trend_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_trend_snapshots_company_id'), 'trend_snapshots', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_snapshots_company_id'), table_name='trend_snapshots')
    op.drop_index(op.f('ix_trend_snapshots_as_of_date'), table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    op.drop_index(op.f('ix_score_snapshots_company_id'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_as_of_date'), table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index(op.f('ix_risk_flags_company_id'), table_name='risk_flags')
    op.drop_index(op.f('ix_risk_flags_as_of_date'), table_name='risk_flags')
    op.drop_table('risk_flags')
    op.drop_index(op.f('ix_ranking_snapshots_company_id'), table_name='ranking_snapshots')
    op.drop_index(op.f('ix_ranking_snapshots_as_of_date'), table_name='ranking_snapshots')
    op.drop_table('ranking_snapshots')
    op.drop_index(op.f('ix_market_snapshots_company_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_as_of_date'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_financials_annual_company_id'), table_name='financials_annual')
    op.drop_table('financials_annual')
    op.drop_index(op.f('ix_sector_configs_sector'), table_name='sector_configs')
    op.drop_table('sector_configs')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
