"""Add unique constraint to ranking_snapshots

Revision ID: 9bc40ce964e0
Revises: b308926353aa
Create Date: 2026-04-21 08:45:43.859614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc40ce964e0'
down_revision: Union[str, Sequence[str], None] = 'b308926353aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ranking_snapshots_company_date_scope', 'ranking_snapshots', ['company_id', 'as_of_date', 'scope'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ranking_snapshots_company_date_scope', 'ranking_snapshots', type_='unique')
    # ### end Alembic commands ###
