"""Add unique constraint to financials_annual

Revision ID: 9d7a1fd34a21
Revises: 88c59fa2b702
Create Date: 2026-04-21 08:26:57.293810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7a1fd34a21'
down_revision: Union[str, Sequence[str], None] = '88c59fa2b702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_financials_annual_company_year', 'financials_annual', ['company_id', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_financials_annual_company_year', 'financials_annual', type_='unique')
    # ### end Alembic commands ###
