"""Add unique constraint to market_snapshots

Revision ID: b308926353aa
Revises: 4c11a6a96499
Create Date: 2026-04-21 08:43:34.483936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b308926353aa'
down_revision: Union[str, Sequence[str], None] = '4c11a6a96499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_market_snapshots_company_date', 'market_snapshots', ['company_id', 'as_of_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_snapshots_company_date', 'market_snapshots', type_='unique')
    # ### end Alembic commands ###
