"""Add unique constraint to score_snapshots

Revision ID: b725abcef74e
Revises: 9bc40ce964e0
Create Date: 2026-04-21 08:48:09.721152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b725abcef74e'
down_revision: Union[str, Sequence[str], None] = '9bc40ce964e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_score_snapshots_company_date', 'score_snapshots', ['company_id', 'as_of_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_score_snapshots_company_date', 'score_snapshots', type_='unique')
    # ### end Alembic commands ###
